name: Build linux-arm64

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g. 4.130.0)"
        type: string
        required: true

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux-arm64:
    name: linux-arm64
    runs-on: ubuntu-22.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ELECTRON_SKIP_BINARY_DOWNLOAD: 1
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      VERSION: ${{ inputs.version }}
      ARCH: arm64
      VSCODE_ARCH: arm64
      npm_config_arch: arm64
      npm_config_build_from_source: true
      VSCODE_TARGET: linux-arm64

    steps:
      - run: sudo apt update && sudo apt install -y libkrb5-dev
      - uses: awalsh128/cache-apt-pkgs-action@553a35bb8ebd9fcabcb1c9451aa4c98e1b4ca8a9
        with:
          packages: quilt
          version: 1.0
      - name: Install nfpm
        run: |
          mkdir -p ~/.local/bin
          curl -sSfL https://github.com/goreleaser/nfpm/releases/download/v2.3.1/nfpm_2.3.1_`uname -s`_`uname -m`.tar.gz | tar -C ~/.local/bin -zxv nfpm
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v6
        with:
          submodules: true
      - run: quilt push -a
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm
          cache-dependency-path: |
            package-lock.json
            test/package-lock.json

      - name: Build
        run: |
          cd lib/vscode/build
          npm ci
          cd ..
          source ./build/azure-pipelines/linux/setup-env.sh
          node build/npm/preinstall.ts
          cd ../..
          npm ci
          npm run build
          npm run build:vscode

      - name: Package release
        run: |
          KEEP_MODULES=1 npm run release
          npm run package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-packages
          path: ./release-packages/*
          retention-days: 30
